**Importing Necessary Libraries**

In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, f_classif, RFE


*Explanation:*
- numpy and pandas: Libraries for numerical operations and data manipulation.
- load_iris: Function from sklearn.datasets to load the Iris dataset.
- train_test_split: Function from sklearn.model_selection to split the dataset into training and testing sets.
- RandomForestClassifier: Ensemble classifier from sklearn.ensemble used as the base estimator for the wrapper method.
- SelectKBest, f_classif, and RFE: Classes and functions from sklearn.feature_selection for feature selection methods.



**Loading Data**


In [4]:
iris = load_iris()
X = iris.data
y = iris.target


*Explanation:*
- load_iris(): Loads the Iris dataset.
- X: Contains the features.
- y: Contains the target variable.


In [5]:
print(iris.data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


**Splitting Data**

In [6]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


*Explanation:*
- train_test_split: Splits the data into training and testing sets.
- X_train, X_test: Training and testing feature sets.
- y_train, y_test: Training and testing target variables.


**Filter Method (SelectKBest)**

In [7]:
# Feature Selection using Filter Method (SelectKBest with ANOVA F-statistic)
k_best = SelectKBest(score_func=f_classif, k=2)
X_train_filtered = k_best.fit_transform(X_train, y_train)
X_test_filtered = k_best.transform(X_test)


*Explanation:*
- SelectKBest: Feature selection method selecting the k best features.
- f_classif: ANOVA F-statistic as the scoring function for classification tasks.
- k=2: Select the top 2 features.
- fit_transform: Fits the transformer on the training set and transforms both training and testing sets.


**Wrapper Method (RFE - Recursive Feature Elimination)**

In [8]:
# Feature Selection using Wrapper Method (Recursive Feature Elimination - RFE)
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rfe = RFE(estimator=rf_classifier, n_features_to_select=2, step=1)
X_train_rfe = rfe.fit_transform(X_train, y_train)
X_test_rfe = rfe.transform(X_test)


*Explanation:*
- RandomForestClassifier: Used as the base estimator for the RFE method.
- n_estimators=100: Number of trees in the Random Forest.
- n_features_to_select=2: Select the top 2 features.
- step=1: Remove one feature at each iteration.
- fit_transform: Fits the transformer on the training set and transforms both training and testing sets.


**Print Selected Features**

In [9]:
# Print selected features using SelectKBest
selected_features_filter = np.array(iris.feature_names)[k_best.get_support()]
print("Selected Features (Filter Method):", selected_features_filter)

# Print selected features using RFE
selected_features_wrapper = np.array(iris.feature_names)[rfe.support_]
print("Selected Features (Wrapper Method):", selected_features_wrapper)

Selected Features (Filter Method): ['petal length (cm)' 'petal width (cm)']
Selected Features (Wrapper Method): ['petal length (cm)' 'petal width (cm)']


*Explanation:*
- k_best.get_support(): Retrieves a boolean mask of selected features from SelectKBest.
- rfe.support_: Retrieves a boolean mask of selected features from RFE.
- Selected features are printed for both the filter and wrapper methods.
